;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Skill.Fatty.LieDown",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Cooldown.Skill.Fatty.Purr",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Cooldown.Skill.Mackerel.Glare",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Cooldown.Skill.Mackerel.HeartBeam",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Cooldown.Skill.Spotted.Cling",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Cooldown.Skill.Spotted.Dominance",DevComment="스킬 쿨다운 부여 태그")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="SetByCaller 쿨다운 지속시간")
+GameplayTagList=(Tag="Data.Damage",DevComment="Attractive Beam base damage")
+GameplayTagList=(Tag="Data.Duration",DevComment="SetByCaller 지속시간 (스턴 등)")
+GameplayTagList=(Tag="Data.SlowMult",DevComment="SetByCaller 이동속도 곱배율 (0.8=20% 감속)")
+GameplayTagList=(Tag="GameplayCue.Cat.Dash",DevComment="")
+GameplayTagList=(Tag="State.RecentAttacked",DevComment="")

