;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Skill.Move.Flash",DevComment="")
+GameplayTagList=(Tag="State.AttractiveInProgress",DevComment="피격 후 7초 유지 — 회복 GE 일시정지용")
+GameplayTagList=(Tag="State.Invulnerable",DevComment="매료 직후 15초 무적")
+GameplayTagList=(Tag="State.Attracted",DevComment="매료 완료 상태")

